### ISSUE TITLE
Make the generator Platform aware

### ISSUE THREAD

**Issue by EP-u-NW** [terrier989/ffi_tool#5]
It would be nice if it was possible to specify different types of loading a native library (e.g. DynamicLibrary.executable, DynamicLibrary.open, DynamicLibrary.process).
Also, it would be useful to give different paths to the libraries on different platforms (and maybe even abis). Currently the Platform class knows 6 different platforms, so they could be easily distinguished.

**Comment by terrier989** [comment]
Hi! I agree with the proposal.

I sent an invitation to become a repository maintainer. Feel free to push directly to the repository if you prefer so. :)

**Comment by terrier989** [comment]
After seeing CI failures, I reverted the recent change because it was a breaking change. It's possible to do it in a backward-compatible manner by introducing a new named parameter.

**Comment by EP-u-NW** [comment]
Agreed. I will commit an update the next two days.

**Comment by EP-u-NW** [comment]
A reworked solution can be found in the develop branch. See #9.
